# Generated by Django 4.1.7 on 2023-03-21 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Klasa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Klasa_Przedmiot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('klasa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dziennik.klasa')),
            ],
        ),
        migrations.CreateModel(
            name='Nauczyciel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=50)),
                ('nazwisko', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('haslo', models.TextField(max_length=100)),
                ('nr_telefonu', models.IntegerField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Przedmiot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.TextField(max_length=100)),
                ('opis', models.TextField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Rodzic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=50)),
                ('nazwisko', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('haslo', models.TextField(max_length=100)),
                ('nr_telefonu', models.IntegerField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Uczen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=50)),
                ('nazwisko', models.CharField(max_length=50)),
                ('adres_zamieszkania', models.CharField(max_length=150)),
                ('pesel', models.IntegerField()),
                ('email', models.CharField(max_length=50)),
                ('haslo', models.TextField(max_length=100)),
                ('klasa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dziennik.klasa')),
            ],
        ),
        migrations.CreateModel(
            name='Rodzic_Uczen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rodzic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dziennik.rodzic')),
                ('uczen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dziennik.uczen')),
            ],
        ),
        migrations.CreateModel(
            name='Ocena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stopien', models.IntegerField(max_length=1)),
                ('opis', models.TextField(max_length=300)),
                ('waga', models.IntegerField()),
                ('data', models.DateField()),
                ('przedmiot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dziennik.klasa_przedmiot')),
                ('uczen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dziennik.uczen')),
            ],
        ),
        migrations.AddField(
            model_name='klasa_przedmiot',
            name='nauczyciel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dziennik.nauczyciel'),
        ),
        migrations.AddField(
            model_name='klasa_przedmiot',
            name='przedmiot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dziennik.przedmiot'),
        ),
        migrations.AddField(
            model_name='klasa',
            name='id_wychowawcy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dziennik.nauczyciel'),
        ),
    ]
