# Generated by Django 4.1.7 on 2023-04-19 19:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dziennik', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rodzic',
            name='user',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='nauczyciel',
            name='nr_telefonu',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ocena',
            name='stopien',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='rodzic',
            name='email',
            field=models.CharField(default='test', max_length=50),
        ),
        migrations.AlterField(
            model_name='rodzic',
            name='haslo',
            field=models.TextField(default='test', max_length=100),
        ),
        migrations.AlterField(
            model_name='rodzic',
            name='imie',
            field=models.CharField(default='test', max_length=50),
        ),
        migrations.AlterField(
            model_name='rodzic',
            name='nazwisko',
            field=models.CharField(default='test', max_length=50),
        ),
        migrations.AlterField(
            model_name='rodzic',
            name='nr_telefonu',
            field=models.IntegerField(default='1234'),
        ),
    ]
