# Generated by Django 4.1.7 on 2023-04-19 19:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dziennik', '0003_rodzic_username_alter_rodzic_email_alter_rodzic_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='nauczyciel',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='uczen',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='nauczyciel',
            name='email',
            field=models.CharField(default='test', max_length=50),
        ),
        migrations.AlterField(
            model_name='nauczyciel',
            name='haslo',
            field=models.TextField(default='test', max_length=100),
        ),
        migrations.AlterField(
            model_name='nauczyciel',
            name='imie',
            field=models.CharField(default='test', max_length=50),
        ),
        migrations.AlterField(
            model_name='nauczyciel',
            name='nazwisko',
            field=models.CharField(default='test', max_length=50),
        ),
        migrations.AlterField(
            model_name='nauczyciel',
            name='nr_telefonu',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='uczen',
            name='adres_zamieszkania',
            field=models.CharField(default='test', max_length=150),
        ),
        migrations.AlterField(
            model_name='uczen',
            name='email',
            field=models.CharField(default='test', max_length=50),
        ),
        migrations.AlterField(
            model_name='uczen',
            name='haslo',
            field=models.TextField(default='test', max_length=100),
        ),
        migrations.AlterField(
            model_name='uczen',
            name='imie',
            field=models.CharField(default='test', max_length=50),
        ),
        migrations.AlterField(
            model_name='uczen',
            name='klasa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dziennik.klasa'),
        ),
        migrations.AlterField(
            model_name='uczen',
            name='nazwisko',
            field=models.CharField(default='test', max_length=50),
        ),
        migrations.AlterField(
            model_name='uczen',
            name='pesel',
            field=models.IntegerField(default=1),
        ),
    ]
